export const INITIAL = {
	destino: "",
	tara: "",
	liquido: "",
	placa: "",
	user: "",
	tipo: "",
	motorista: "",
	pesoBruto: "",
	fazendaOrigem: "",
	createdAt: "",
	impureza: "",
	umidade: "",
	relatorioColheita: "",
	fazendaDestino: "",
	parcelasNovas: [],
	cultura: "",
	projeto: "",
	parcela: "",
	entrada: "",
	unidadeOp: "",
	mercadoria: "", // variedade
	saida: "-",
	origem: "",
	valorFrete: "",
	ticket: "",
	observacoes: "",
	nfEntrada: "",
	op: "",
	id: "" // firebaseId
};
